name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t anand564/anand-server:latest .

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: testrbi.bkukqa@gmail.com
          password: Anand@564

      - name: Push Docker Image
        run: |
          docker push anand564/anand-server:latest